### ISSUE TITLE
PlayWright+Cucumber+ Allure - Allure is not supporting for latest cucumber version 10.8.0

### ISSUE THREAD

**Issue by varshanharshank** [allure-framework/allure-js#1082]
**Describe the bug**
I unable to run cucumber.js file after migrating to the cucumber 10.8 version.It is showing below error. 

**Error: Failed to import formatter ./src/helper/report/allureReport.ts
    at importCode (/Users/test/Documents/Workspace/purpleportalautomation/node_modules/@cucumber/cucumber/src/formatter/import_code.ts:14:11)
    at async resolveImplementation (/Users/test/Documents/Workspace/purpleportalautomation/node_modules/@cucumber/cucumber/src/formatter/resolve_implementation.ts:13:22)
    at async initializeFormatter (/Users/test/Documents/Workspace/purpleportalautomation/node_modules/@cucumber/cucumber/src/api/formatters.ts:51:28)
    at async initializeFormatters (/Users/test/Documents/Workspace/purpleportalautomation/node_modules/@cucumber/cucumber/src/api/formatters.ts:86:5)
    at async runCucumber (/Users/test/Documents/Workspace/purpleportalautomation/node_modules/@cucumber/cucumber/src/api/run_cucumber.ts:93:29)
    at async Cli.run (/Users/test/Documents/Workspace/purpleportalautomation/node_modules/@cucumber/cucumber/src/cli/index.ts:79:25)
    at async Object.run [as default] (/Users/test/Documents/Workspace/purpleportalautomation/node_modules/@cucumber/cucumber/src/cli/run.ts:32:14) {
  [cause]: TypeError: Unknown file extension ".ts" for /Users/test/Documents/Workspace/purpleportalautomation/src/helper/report/allureReport.ts**
  
  **Note**:
  It is not allowing to import below
  import { CucumberAllureWorld } from 'allure-cucumberjs'
  
  
**To Reproduce**

Migrate cucumber version to latest 10.8
Run the following command npx cucumber-js test --tags '@smoke'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac sonoma 14.5
 - Browser chrome

//allureReport.ts

/* eslint-disable @typescript-eslint/no-explicit-any */
import { AllureRuntime, CucumberJSAllureFormatter } from 'allure-cucumberjs'

function Reporter(options: any) {
  return new CucumberJSAllureFormatter(
    options,
    new AllureRuntime({ resultsDir: 'reports/allure-results' }),
    {
      labels: [
        {
          name: 'epic',
          pattern: [/@feature:(.*)/],
        },
        {
          name: 'severity',
          pattern: [/@severity:(.*)/],
        },
      ],
      links: [
        {
          type: 'issue',
          pattern: [/@issue=(.*)/],
          urlTemplate: 'http://localhost:8080/issue/%s',
        },
        {
          type: 'tms',
          pattern: [/@tms=(.*)/],
          urlTemplate: 'http://localhost:8080/tms/%s',
        },
      ],
    }
  )
}

Reporter.prototype = Object.create(CucumberJSAllureFormatter.prototype)
Reporter.prototype.constructor = Reporter

exports.default = Reporter

cucumber.json
```
{
  "default": {
    "paths": ["src/test/features"],
    "require": ["src/test/stepDefinitions/*.ts", "src/hooks/hooks.ts"],
    "requireModule": ["ts-node/register"],
    "publishQuiet": true,
    "format": [
      "progress-bar",
       "./src/helper/report/allureReport.ts:./output.txt",
      "html:reports/cucumberReport/cucumber-report.html",
      "json:reports/cucumberReport/cucumber-report.json"
    ],
    "parallel": 1
  }
}

```

package.json

<img width="697" alt="image" src="https://github.com/user-attachments/assets/0dcf659b-24b1-4699-9668-9458d175f69a">

**Comment by SwikritiT** [comment]
I'm also having the same problem

**Comment by MaksymZup** [comment]
same problem

**Comment by rudyaditya** [comment]
same issue
`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" `
I already put this
`requireModule: ['ts-node/register'],`

**Comment by arcaneGamer888** [comment]
Same issue. When will this be fixed?

**Comment by oleg-lukasonok-medium** [comment]
Did anyone tried instead of 

```
ts-node/register
```

to use 

```
ts-node/esm
```
?

More here: 

https://github.com/cucumber/cucumber-js/blob/main/docs/transpiling.md

**Comment by baev** [comment]
We have official examples for all the possible combinations of build system (NPM, PNPM, Yarn), language (JavaScript, TypeScript) and module system (CommonJS, ESM). Please see https://github.com/allure-examples?q=cucumberjs&type=all&language=&sort=

For ESM, it works if using `ts-node/esm`: https://github.com/allure-examples/cucumberjs-npm-esm-ts/blob/main/package.json#L8

However, due to issues in `ts-node/esm` (it expects node-modules directory to be present), for Yarn PNP, the only option so far is to use `nodeLinker: node-modules`: https://github.com/allure-examples/cucumberjs-yarn-esm-ts/blob/main/.yarnrc.yml#L1
