### ISSUE TITLE
[Cypress] Tests fails on `reportAllureCypressSpecMessages` task

### ISSUE THREAD

**Issue by M-Burzynski** [allure-framework/allure-js#1133]
**Describe the bug**
When using the `allure-cypress` with the `cypress-plugin-snapshots` for visual regression tests, when a test fails on a screenshot comparison, then the after hook fails with an error:
```
CypressError: cy.task('reportAllureCypressSpecMessages') fails with the following error:
> ENOENT: no such file or directory, copyfile '/var/lib/jenkins/workspace/project-name/cypress/screenshots/spec_name.cy.js/screenshot_name #0.png' -> 'cypress/reports/allure-results/81429aaa-74cf-49ff-8c2c-447d718fa405-attachment.png'
https://on.cypress.io/api/task
Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
      at <unknown> (http://localhost:4173/__cypress/runner/cypress_runner.js:135481:70)
      at tryCatcher (http://localhost:4173/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:4173/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://localhost:4173/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://localhost:4173/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://localhost:4173/__cypress/runner/cypress_runner.js:1697:18)
      at _drainQueueStep (http://localhost:4173/__cypress/runner/cypress_runner.js:2407:12)
      at _drainQueue (http://localhost:4173/__cypress/runner/cypress_runner.js:2400:9)
      at Async._drainQueues (http://localhost:4173/__cypress/runner/cypress_runner.js:2416:5)
      at Async.drainQueues (http://localhost:4173/__cypress/runner/cypress_runner.js:2286:14)
  From Your Spec Code:
      at $.flushAllureMessagesToTask (webpack:///../../node_modules/allure-cypress/dist/cjs/index.js:1:12072)
      at [Context.ee](http://context.ee/) (webpack:///../../node_modules/allure-cypress/dist/cjs/index.js:1:14228)
```
As `cypress-plugin-snapshots` stores visual regresion screenshots inside a folder `e2e/spec_name` but the `allure-cypress` plugin tries to copy all the screenshots taken during test run and assumes they all are saved inside `screenshots` folder, so it tries to copy screenshots from the path which is not correct.
Is there any way to configure which screenshots should be copied and which not? Or any other way to avoid this problem and ignore the fail in after hook?
Currently the whole tests suite stops when this error occurs.

**To Reproduce**
1. Set up the `cypress-plugin-snapshots` and `allure-cypress` plugin in the repository
2. Run the test script in which a screenshot comparison would fail
3. See error described at the beginning

**Expected behavior**
`allure-cypress` plugin shouldn't try to copy attatchments from non existing paths or it should be possible to configure which attatchments should be copied to the report.
**Screenshots**

![image](https://github.com/user-attachments/assets/ef27313e-4a33-43be-898b-7494032f4650)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]
 - allure-cypress Version [v3.0.0-beta.11]
 - Cypress version [13.14.1]

**Comment by nayanakb9** [comment]
Facing the same error. 
Please let know how to resolve

**Comment by kwangecs** [comment]
Facing similar issue with version  
allure-cypress Version "^3.0.6"
Cypress version [13.13]
Browser [chrome]
OS: [Mac]

<img width="529" alt="Screenshot 2024-11-01 at 2 24 58 PM" src="https://github.com/user-attachments/assets/90913385-9992-47ef-8021-0953412ad408">

**Comment by sajeerk123** [comment]
I am facing same issue.
My cypress.config.js 
`const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here

    },
    specPattern:'cypress/e2e/getting-started/*.js'
  },
});`
![image](https://github.com/user-attachments/assets/5292978a-c51a-4eda-b6cc-b6e7f4ae2623)

Cypress version : 13.15.1

**Comment by diefersoncruz** [comment]
Try with this config on your cypress.config.js

 env: {
      preserveOriginalScreenshot: true,
    },

**Comment by baev** [comment]
@M-Burzynski, could you please specify the versions of `cypress`, `allure-cypress` and `cypress-plugin-snapshots`?

**Comment by M-Burzynski** [comment]
> [@M-Burzynski](https://github.com/M-Burzynski), could you please specify the versions of `cypress`, `allure-cypress` and `cypress-plugin-snapshots`?

@baev Today I checked it on the newest versions and issue still exists:
`cypress` 14.0.0
`allure-cypress` 3.0.9
`cypress-plugin-snapshots` 1.4.4

**Comment by baev** [comment]
Thanks, we'll take a look shortly.

**Comment by nasvaytrip** [comment]
Is there any updates on this issue? 
I have the same error. 
`cypress` 13.17.0
`node ` 14.21.3 
`allure-cypress` 3.0.6
If i will use the node 16 then the report will be generated successfully.

**Comment by baev** [comment]
Support for Node versions < 18 has been dropped since release 3.0.0. 

> Allure Cypress is tested against Node.js 18 and higher. Older versions may work, but we can't guarantee that.

https://allurereport.org/docs/cypress/

There are no plans to support earlier versions. We usually follow the official Node release schedule, dropping support for unmaintained versions, see: https://nodejs.org/en/about/previous-releases

**Comment by M-Burzynski** [comment]
hello, coming back here after 1,5 year and verified it on ver. 3.9.0, but sadly this issue still exists and is a blocker for me :( is it planned to be fixed?
