### ISSUE TITLE
[Jasmine] Jest with testRunner: jasmine2 - test run fails because of an undefined spec.filename

### ISSUE THREAD

**Issue by delatrie** [allure-framework/allure-js#1169]
**Describe the bug**
When using allure-jasmine with Jest, the following error is thrown:

```text
TypeError: The "path" argument must be of type string. Received undefined
        at Object.isAbsolute (node:path:435:5)
        at isAbsolute (C:\Users\madam\repos\jasmine-test\node_modules\allure-js-commons\src\sdk\reporter\utils.ts:105:12)
        at getPackageLabel (C:\Users\madam\repos\jasmine-test\node_modules\allure-js-commons\src\sdk\reporter\utils\labels.ts:49:25)
        at C:\Users\madam\repos\jasmine-test\node_modules\allure-jasmine\src\index.ts:156:41
        at ReporterRuntime.updateFunc (C:\Users\madam\repos\jasmine-test\node_modules\allure-js-commons\src\sdk\reporter\ReporterRuntime.ts:226:5)
        at AllureJasmineReporter.updateTest [as specDone] (C:\Users\madam\repos\jasmine-test\node_modules\allure-jasmine\src\index.ts:147:24)
        at dispatch (C:\Users\madam\repos\jasmine-test\node_modules\jest-jasmine2\build\jasmine\ReportDispatcher.js:87:28)
        at ReportDispatcher.specDone (C:\Users\madam\repos\jasmine-test\node_modules\jest-jasmine2\build\jasmine\ReportDispatcher.js:63:11)
        at Object.specResultCallback (C:\Users\madam\repos\jasmine-test\node_modules\jest-jasmine2\build\jasmine\Env.js:429:20)
        at Spec.attr.resultCallback (C:\Users\madam\repos\jasmine-test\node_modules\jest-jasmine2\build\setup_jest_globals.js:60:26)
        at complete (C:\Users\madam\repos\jasmine-test\node_modules\jest-jasmine2\build\jasmine\Spec.js:172:12)
        at C:\Users\madam\repos\jasmine-test\node_modules\jest-jasmine2\build\jasmine\Spec.js:169:32
```

The test run then hangs until ctrl+C is pressed.

**To Reproduce**
1. `npx install --save-dev jest jest-jasmine2 allure-jasmine`
2. In `jest.config.json`:
    ```json
    {
        "testRunner": "jasmine2",
        "setupFilesAfterEnv": [
            "./spec/helpers/allure.js"
        ]
    }
    ```
4. In `./spec/helpers/allure.js`:
    ```js
    const AllureJasmineReporter = require("allure-jasmine");

    jasmine.getEnv().addReporter(
      new AllureJasmineReporter(),
    );
    ```
5. Add a spec file.
6. `npx jest`
7. Observe the error.

**Expected behavior**
No error; test results are generated.

**Desktop (please complete the following information):**
 - OS: Windows
 - Integration version allure-jasmine@3.0.5
 - Jest version: jest@29.7.0

**Comment by delatrie** [comment]
Duplicate of #1168
