### ISSUE TITLE
registerHandler is not a function when trying to use cucumberjs reporter

### ISSUE THREAD

**Issue by Jiff21** [allure-framework/allure-js#203]
#### I'm submitting a ... 
  - [X ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
`this.registerHandler is not a function` error 

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Node v10.16.3
Cucumber.js 6.0.5 or 5.1.0 (just ones I tested with)
allure-cucumberjs 2.0.0-beta.7
also tried cucumberjs-allure-reporter 1.0.3 just in case.

When trying to run with `./node_modules/cucumber/bin/cucumber-js ./features --format ./allure/reporter.js -r ./steps`
reporter.js  contents match suggested content https://docs.qameta.io/allure/#_usage_4
```
var reporter = require('cucumberjs-allure-reporter');
reporter.config({targetDir: "../allure/results"});
module.exports = reporter;
```
I thought it was related to breaking changing in cucumberjs, https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#breaking-changes, but it seems to be occurring on 5.1.0.  
I also tried the github suggested, https://github.com/allure-framework/allure-js/blob/master/packages/allure-cucumberjs/README.md
```
var CucumberJSAllureFormatter = require(allure-cucumberjs).CucumberJSAllureFormatter;
var AllureRuntime = require(allure-cucumberjs).AllureRuntime;

function Reporter(options) {
  CucumberJSAllureFormatter.call(this,
    options,
    new AllureRuntime({ resultsDir: "./out/allure-results" }),
    {});
}
Reporter.prototype = Object.create(CucumberJSAllureFormatter.prototype);
Reporter.prototype.constructor = Reporter;

exports.default = Reporter;
```
but get a `allure is not defined`. 

#### What is the expected behavior?
Generates results data or explain which version of cucumberjs are supported in main documentation (https://docs.qameta.io/allure/#_usage_4 and/or github page of this repo). (It would also be helpful to say if it's  `npm i allure-cucumberjs` or `npm i cucumberjs-allure-reporter` (as it seems documentation mentions this in import) or `npm i cucumberjs-allure2-reporter` (as this stackoverflow issue suggests https://stackoverflow.com/questions/53544153/unable-to-generate-allure-report-for-protractor-cucumber).

#### Other information 
```
TypeError: this.registerHandler is not a function
    at new Reporter (/Users/name/Documents/Code/puppet-ga/node_modules/cucumberjs-allure-reporter/src/CucumberJSAllureReporter.js:14:10)
    at Function.build (/Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/formatter/builder.js:49:12)
    at /Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:121:35
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:44:103)
    at _next (/Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:46:194)
    at /Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:46:364
    at new Promise (<anonymous>)
    at /Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:46:97
    at /Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:125:23
    at tryCatcher (/Users/name/Documents/Code/puppet-ga/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/name/Documents/Code/puppet-ga/node_modules/bluebird/js/release/map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/name/Documents/Code/puppet-ga/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/Users/name/Documents/Code/puppet-ga/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/Users/name/Documents/Code/puppet-ga/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/Users/name/Documents/Code/puppet-ga/node_modules/bluebird/js/release/async.js:97:12)
```
Or on Readme Version
```
ReferenceError: allure is not defined
    at Object.<anonymous> (/Users/name/Documents/Code/puppet-ga/allure/reporter.js:5:41)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Function.loadCustomFormatter (/Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/formatter/builder.js:115:29)
    at Function.getConstructorByType (/Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/formatter/builder.js:82:33)
    at Function.build (/Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/formatter/builder.js:42:40)
    at /Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:121:35
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:44:103)
    at _next (/Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:46:194)
    at /Users/name/Documents/Code/puppet-ga/node_modules/cucumber/lib/cli/index.js:46:364
```

**Comment by Jiff21** [comment]
This is working on allure-cucumberjs@2.0.0-beta.8.

Using this reporter in that versions readme.
```
const { CucumberJSAllureFormatter } = require("allure-cucumberjs");
const { AllureRuntime } = require("allure-cucumberjs");

function Reporter(options) {
  return new CucumberJSAllureFormatter(
    options,
    new AllureRuntime({ resultsDir: "./path/to/results" }),
    {}
  );
}
Reporter.prototype = Object.create(CucumberJSAllureFormatter.prototype);
Reporter.prototype.constructor = Reporter;

exports.default = Reporter;
```
