### ISSUE TITLE
Get result.steps is not iterable when trying to use allure-playwright

### ISSUE THREAD

**Issue by abhatia1994** [allure-framework/allure-js#413]
**Describe the bug**
I am trying to use allure-playwright(version: ^2.0.0-beta.14). All the tests pass and i keep getting the following error when I add `allure-playwright` as one of the reporters in my playwright.config file.

```
TypeError: result.steps is not iterable
    at processSuite (/Users/abhatia/Documents/aura2/packages/aura-petals/node_modules/allure-playwright/src/index.ts:87:37)
    at processSuite (/Users/abhatia/Documents/aura2/packages/aura-petals/node_modules/allure-playwright/src/index.ts:129:9)
    at processSuite (/Users/abhatia/Documents/aura2/packages/aura-petals/node_modules/allure-playwright/src/index.ts:129:9)

```
The allure-results folder is created, but its empty
**To Reproduce**
1. just run `npx playwright test`

**Expected behavior**

**Screenshots**
<img width="940" alt="image" src="https://user-images.githubusercontent.com/27016980/145076922-1de85684-c7f2-4c93-a777-d0e748470fcc.png">

**Comment by baev** [comment]
should be fixed by now
