### ISSUE TITLE
[ALLURE-PLAYWRIGHT] How to use the Jira plugin?

### ISSUE THREAD

**Issue by DvDream** [allure-framework/allure-js#438]
Hi, I need to link my Allure-report results to some Jira issue links. I found this plugin that seems to be useful https://github.com/allure-framework/allure2/blob/master/plugins/jira-plugin/README.md 

I'm using the latest release of allure-playwright and I have the latest jira-plugin installed to Jira, but I'm not understanding how to get this working.

First question: in the `ALLURE_JIRA_ENDPOINT=https://<jira>/jira/rest/` what should be written instead of `<jira>`? 
 I managed to set up the other env variables as the documentation says. In my test I write:

`        allure.issue({
            url: *link-to-issue*,
            name: "issue-name",
        });`

when the test finishes the allure-results folder is created. Then I launch the command:

`npx allure generate ./allure-results --clean`

Then I get this error: 

`Allure launch sync with issue '[]' error
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "exportResults" is null
        at io.qameta.allure.jira.JiraExportPlugin.findFailuresInExportResult(JiraExportPlugin.java:157)
        at io.qameta.allure.jira.JiraExportPlugin.exportLaunchToJira(JiraExportPlugin.java:104)
        at io.qameta.allure.jira.JiraExportPlugin.aggregate(JiraExportPlugin.java:82)
        at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
        at io.qameta.allure.Commands.generate(Commands.java:104)
        at io.qameta.allure.CommandLine.run(CommandLine.java:152)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.qameta.allure.CommandLine.main(CommandLine.java:88)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "exportResults" is null
        at io.qameta.allure.jira.JiraExportPlugin.findFailuresInExportResult(JiraExportPlugin.java:157)
        at io.qameta.allure.jira.JiraExportPlugin.exportLaunchToJira(JiraExportPlugin.java:104)
        at io.qameta.allure.jira.JiraExportPlugin.aggregate(JiraExportPlugin.java:82)
        at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
        at io.qameta.allure.Commands.generate(Commands.java:104)
        at io.qameta.allure.CommandLine.run(CommandLine.java:152)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.qameta.allure.CommandLine.main(CommandLine.java:88)`

However, the allure-report folder is generated but I cannot see anything about this report result in my jira issue link..
Also, as the doc says, in the allure-results folder there is no `executor.json` folder and I don't know if this is the problem and how it should be structured.

Can anyone help me with this issue? Thank you!

**Comment by DvDream** [comment]
I found the issue: I was using a wrong endpoint for Jira.

In my case all I needed to do was to change:

`ALLURE_JIRA_ENDPOINT=https://<jira>/jira/rest/`

to 

`ALLURE_JIRA_ENDPOINT=https://<jira>/rest/`
