### ISSUE TITLE
Allure Report generator throws an exception when handling html attachment

### ISSUE THREAD

**Issue by zcsteele** [allure-framework/allure-js#487]
**Describe the bug**
The allure reporter does not support test attachments of type "text/html", and throws an exception during testbed execution 

**To Reproduce**
1. Configure a playwright test run to use the allure-playwright integration
2. Add code to one of the test cases to generate an attachment with content-type "text/html":
   ```
   testInfo.attach('Hyperlink attachment', {
       body: '<a href="http://example.com" target="_blank">http://example.com</a>',
       contentType: 'text/html',
   });
3. Execute a test run including the test with the attachment operation
4. When the test case completes the following stack trace is reported in the console:
```
Error in reporter Error: Unrecognized extension: text/html
    at typeToExtension (/Users/administrator/Developer/web/node_modules/allure-js-commons/src/writers/utils.ts:3:14)
    at buildAttachmentFileName (/Users/administrator/Developer/web/node_modules/allure-js-commons/src/AllureRuntime.ts:12:36)
    at AllureRuntime.writeAttachment (/Users/administrator/Developer/web/node_modules/allure-js-commons/src/AllureRuntime.ts:45:22)
    at AllureReporter.onTestEnd (/Users/administrator/Developer/web/node_modules/allure-playwright/src/index.ts:151:28)
    at /Users/administrator/Developer/web/node_modules/@playwright/test/lib/reporters/multiplexer.js:69:131
    at wrap (/Users/administrator/Developer/web/node_modules/@playwright/test/lib/reporters/multiplexer.js:119:5)
    at Multiplexer.onTestEnd (/Users/administrator/Developer/web/node_modules/@playwright/test/lib/reporters/multiplexer.js:66:45)
    at Dispatcher._reportTestEnd (/Users/administrator/Developer/web/node_modules/@playwright/test/lib/dispatcher.js:574:159)
    at Worker.onTestEnd (/Users/administrator/Developer/web/node_modules/@playwright/test/lib/dispatcher.js:240:12)
    at Worker.emit (node:events:526:28)
    at ChildProcess.<anonymous> (/Users/administrator/Developer/web/node_modules/@playwright/test/lib/dispatcher.js:633:12)
```

**Expected behavior**
The test run should execute without throwing any exceptions.
(Rendering logic for the generated report is outside the scope of this issue, I just need the exception to not be thrown)

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1
 - Browser: Any (observed while running playwright with chromium, webkit, and chromium mobile emulation)

**Additional context**
This issue was observed while running tests using the allure-playwright reporter, but based on the exception's stack trace this issue applies to any test code used to generate allure reports.

**Comment by zcsteele** [comment]
I have started a PR that fixes this issue by adding the `text/html` content-type to the models: https://github.com/allure-framework/allure-js/pull/488

Test code is TBD, but I'm using this code in my local project via `yarn patch` for the moment.
