### ISSUE TITLE
Error on Allure generate command

### ISSUE THREAD

**Issue by DvDream** [allure-framework/allure-js#521]
I'm trying to execute the allure generate command through Node.js exec child process command in this way:

```
const stdout = await exec(`npx allure generate ./allure-reports/2022-11-22_14_41_59_301_/allure-results -o ./allure-reports/2022-11-22_14_41_59_301_/allure-report --clean`)
```
this is because I have a web app that execute this code automatically after the tests have finished running. However, I'm having this issue in console:

```
Could not generate report
java.nio.file.FileSystemException: ./allure-reports/2022-11-22_14_41_59_301_/allure-report/widgets/history-trend.json: Numerical result out of range
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at io.qameta.allure.CommonJsonAggregator.aggregate(CommonJsonAggregator.java:53)
        at io.qameta.allure.CompositeAggregator.aggregate(CompositeAggregator.java:43)
        at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
        at io.qameta.allure.Commands.generate(Commands.java:103)
        at io.qameta.allure.CommandLine.run(CommandLine.java:160)
        at java.util.Optional.orElseGet(Optional.java:267)
        at io.qameta.allure.CommandLine.main(CommandLine.java:92)
```

and these are my dependencies:

    "allure-commandline": "^2.20.1",
    "allure-playwright": "^2.0.0-beta.19"

and thisis the info about the file history-trend:

`-rwxrwxrwx. 1 root root 3.2K Nov 22 15:43 history-trend.json`

can someone help on what could it be? Thank you!

**Comment by vovsemenv** [comment]
Hello @DvDream  actually `npx allure generate` just execute java based generator. can you share allure-results folder to troubleshoot? Or create repo with reproduction it will be very helpful
