### ISSUE TITLE
Could not read test result file allure-results\<file-name-here>.json

### ISSUE THREAD

**Issue by ericrommel** [allure-framework/allure-js#573]
I'm using `newman-report-allure` to generate the `newman` execution. After the running, all test results are there, however, the report is empty and from the server log, the error below for all test result file generated is showed:

```shell
Could not read test result file allure-results\fe1bdaef-35b0-4b54-8b34-808d69cbc3ce-result.json
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "excluded" (class io.qameta.allure.model.Parameter), not marked as ignorable (2 known properties: "value", "name"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 1552] (through reference chain: io.qameta.allure.model.TestResult["parameters"]->java.util.ArrayList[2]->io.qameta.allure.model.Parameter["excluded"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3585)
        at io.qameta.allure.allure2.Allure2Plugin.readTestResult(Allure2Plugin.java:344)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:104)
        at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:47)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:47)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:69)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
        at io.qameta.allure.Commands.generate(Commands.java:104)
        at io.qameta.allure.Commands.serve(Commands.java:129)
        at io.qameta.allure.CommandLine.run(CommandLine.java:159)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.qameta.allure.CommandLine.main(CommandLine.java:88)
```

**My `package.json` file:**
```json
{
  "name": "newman-postman",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "newman run collection.json -e env.json --reporters allure --reporter-allure-export allure-results"
  },
  "homepage": "--",
  "dependencies": {
    "newman": "^5.3.2",
    "newman-reporter-allure": "^2.0.0-beta.24"
  }
}
```
**Steps to reproduce:**
1. Create a sample collection and environment in Postman and export them (names suggested in the `package.json`)
2. `npm test` to run `newman` and have the test result generated
3. `allure serve allure-results\` to see the report from Allure

Note: Same happens with `allure generate --clean` command.

```shell
$ allure --version
2.14.0
```
```shell
$ newman -v
5.3.2
```
```shell
$ node -v
v19.4.0
```
```shell
$ npm -v
9.2.0
```

There is something similar for `allure-python`: https://github.com/allure-framework/allure-python/issues/378.
Maybe this is the same issue from there.

Is this really a bug or there is some workaround?

**Comment by vovsemenv** [comment]
Hello @ericrommel. thank you for sharing this bug. Can you problematic `allure-results\fe1bdaef-35b0-4b54-8b34-808d69cbc3ce-result.json` result file?

**Comment by ericrommel** [comment]
Hi @vovsemenv, is there a way to send it privately?

**Comment by baev** [comment]
simply upgrade your allure-commandline to the latest version
