### ISSUE TITLE
[Allure-playwright] Unrecognized field "mode" (class io.qameta.allure.model.Parameter), not marked as ignorable (2 known properties: "value", "name"])

### ISSUE THREAD

**Issue by jpinheiro27** [allure-framework/allure-js#618]
**Describe the bug**
Using the Parameters usage examples provided in the https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md#parameters-usage, the allure report is not generated and I got the error bellow: 
```
Unrecognized field "mode" (class io.qameta.allure.model.Parameter), not marked as ignorable (2 known properties: "value", "name"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 4799] (through reference chain: io.qameta.allure.model.TestResult["parameters"]->java.util.ArrayList[0]->io.qameta.allure.model.Parameter["mode"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3585)
        at io.qameta.allure.allure2.Allure2Plugin.readTestResult(Allure2Plugin.java:344)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:104)
        at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:47)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:47)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:69)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
        at io.qameta.allure.Commands.generate(Commands.java:104)
        at io.qameta.allure.CommandLine.run(CommandLine.java:152)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.qameta.allure.CommandLine.main(CommandLine.java:88)
Report successfully generated to allure-report
Starting web server...

```
![image](https://user-images.githubusercontent.com/26628269/220105984-8ea7695a-6fa7-47ca-8e64-1c83de385894.png)

**To Reproduce**
1. Include the code `allure.addParameter("parameterName", "parameterValue", { mode: "hidden" })` in a test spec file and execute it;
2. Generate the allure report `allure generate ./allure-results --clean && allure open ./allure-report`

**Expected behavior**
The allure report should be generated successfully, with the parameter on hidden mode. 

Version:
@playwright/test": "^1.30.0",
"allure-playwright": "^2.0.0",

**Comment by baev** [comment]
BTW since `2.11` Allure will ignore unknown fields in the results
