### ISSUE TITLE
Unable to attach a screenshot with contentType: "application/vnd.allure.image.diff" 

### ISSUE THREAD

**Issue by zyab1ik** [allure-framework/allure-js#673]
**Describe the bug**
Unable to attach a screenshot with contentType: "application/vnd.allure.image.diff". Unrecognized extension:  application/vnd.allure.image.diff

**To Reproduce**
1. Import allure adapter in test: `const allure = codeceptjs.container.plugins('allure');`
2. Create allure attachment with contentType - application/vnd.allure.image.diff' and try to run test
```javascript
allure.addAttachment(
    filename,
    JSON.stringify({
      name: filename,
      expected: `data:image/png;base64,${expected.toString('base64')}`,
      actual: `data:image/png;base64,${actual.toString('base64')}`,
      diff: diff.getImageDataUrl(),
    }),
    'application/vnd.allure.image.diff',
  );
``` 
3. See error:
```shell
Unrecognized extension: application/vnd.allure.image.diff
      at typeToExtension (node_modules/allure-js-commons/src/writers/utils.ts:37:9)
      at buildAttachmentFileName (node_modules/allure-js-commons/src/AllureRuntime.ts:12:36)
      at AllureRuntime.writeAttachment (node_modules/allure-js-commons/src/AllureRuntime.ts:46:22)
``` 

**Expected behavior**
Support content type - 'application/vnd.allure.image.diff', see image diff in allure 

**Screenshots**
<img width="574" alt="Screenshot 2023-05-05 at 4 41 56 PM" src="https://user-images.githubusercontent.com/63905645/236474703-cbe6bffa-5f6d-4f7c-afa6-583aa4a7f03e.png">

**Devices:**
- Doesn't matter

**Additional context**
- Allure CodeceptJS adapter 2.2.1 - https://github.com/allure-framework/allure-js/blob/master/packages/allure-codeceptjs/README.md
- codecept.conf.ts:
```javascript
  allure: {
      enabled: true,
      require: "allure-codeceptjs",
      outputDir: './output',
      enableScreenshotDiffPlugin: true,
      detail: true,
      suiteTitle: false,
    },
``` 

- Could you update documentation and examples of using this method ?

**Comment by zyab1ik** [comment]
Thank you!
