### ISSUE TITLE
[CodeceptJS integration] - Something went wrong error when trying to add the attachment.

### ISSUE THREAD

**Issue by kobenguyent** [allure-framework/allure-js#703]
**Describe the bug**
[CodeceptJS integration] - Something went wrong error when trying to add the attachment.

**To Reproduce**
1. Clone https://github.com/kobenguyent/codeceptjs-a11y-helper
2. Run npm i
3. Cd to test/ folder
4. Run npm i 
5. Run npm i allure-codeceptjs
6. Change the configuration https://github.com/kobenguyent/codeceptjs-a11y-helper/blob/main/test/codecept.conf.ts#L22 to `require: "allure-codeceptjs"`
7. Run the test with npx codeceptjs run --verbose

**Expected behavior**
No error, the attachment is successful

**Screenshots**
`    Something went wrong Error: Something went wrong
    at AllureReporter.debug (/Users/thanh.nguyen/Desktop/codeceptjs-a11y-helper/test/node_modules/allure-codeceptjs/src/index.ts:333:19)
    at AllureReporter.get currentAllureTest [as currentAllureTest] (/Users/thanh.nguyen/Desktop/codeceptjs-a11y-helper/test/node_modules/allure-codeceptjs/src/index.ts:340:7)
    at AllureReporter.addAttachment (/Users/thanh.nguyen/Desktop/codeceptjs-a11y-helper/test/node_modules/allure-codeceptjs/src/index.ts:359:4)
    at A11yHelper._attachArtifacts (/Users/thanh.nguyen/Desktop/codeceptjs-a11y-helper/src/index.ts:127:14)
    at async A11yHelper._passed (/Users/thanh.nguyen/Desktop/codeceptjs-a11y-helper/src/index.ts:110:4)
`
![Screenshot 2023-06-19 at 10 16 30](https://github.com/allure-framework/allure-js/assets/7845001/9caa9f96-ac6f-4b8b-a75d-f9971c27f593)

**Desktop (please complete the following information):**
nodeInfo:  18.16.0
osInfo:  macOS 13.3.1
cpuInfo:  (8) arm64 Apple M1 Pro
chromeInfo:  114.0.5735.133

**Comment by epszaw** [comment]
The problem can't be reproduced in the next coming version (`3.0.0-beta.4`). Probably, it was solved earlier.
