### ISSUE TITLE
allure-playwright 2.8.0 - Error: Cannot find module 'uuid'

### ISSUE THREAD

**Issue by StasGrishaevTutu** [allure-framework/allure-js#775]
**Describe the bug**

Immediately after updating to version 2.8.0, running any of the tests instantly fails with an error, I am attaching an example of the stack.

```
/Users/grishaev/.nvm/versions/node/v18.12.1/bin/node /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/cli.js test /Users/grishaev/Documents/user-space-ui-tests/tests/functional/open-hotel-link.spec.ts -g  Open hotel link @smoke --reporter /Applications/Aqua 2023.2 EAP.app/Contents/plugins/aqua-plugin/reporting/playwright/playwrightReporter.js
Error: Cannot find module 'uuid'
Require stack:
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/allure-playwright/dist/helpers.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/allure-playwright/dist/index.js
- /Users/grishaev/Documents/user-space-ui-tests/helpers/allure-helper.ts
- /Users/grishaev/Documents/user-space-ui-tests/tests/setup/base-test.ts
- /Users/grishaev/Documents/user-space-ui-tests/tests/functional/open-hotel-link.spec.ts
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/lib/transform/transform.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/lib/common/config.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/lib/reporters/json.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/lib/reporters/raw.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/lib/reporters/html.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/lib/runner/reporters.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/lib/runner/runner.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/lib/cli.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/@playwright/test/cli.js
    at Object.<anonymous> (/Users/grishaev/Documents/user-space-ui-tests/node_modules/allure-playwright/src/helpers.ts:13:1)
    at Object.<anonymous> (/Users/grishaev/Documents/user-space-ui-tests/node_modules/allure-playwright/src/index.ts:453:1)
    at Object.<anonymous> (/Users/grishaev/Documents/user-space-ui-tests/helpers/allure-helper.ts:2:1)
    at Object.<anonymous> (/Users/grishaev/Documents/user-space-ui-tests/tests/setup/base-test.ts:2:1)
    at Object.<anonymous> (/Users/grishaev/Documents/user-space-ui-tests/tests/functional/open-hotel-link.spec.ts:1:1)
Error: Cannot find module 'uuid'
Require stack:
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/allure-playwright/dist/helpers.js
- /Users/grishaev/Documents/user-space-ui-tests/node_modules/allure-playwright/dist/index.js
- /Users/grishaev/Documents/user-space-ui-tests/helpers/allure-helper.ts
- /Users/grishaev/Documents/user-space-ui-tests/tests/setup/base-test.ts
```

**To Reproduce**
1. Update allure-playwright to 2.8.0
2. Run any test

**Expected behavior**
The test will be passed

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2
 - Browser Chromium
 - Version 116

**Comment by serembon** [comment]
Same error
