### ISSUE TITLE
 Error: ENOENT: no such file or directory, open <file_name>.txt on Node.js v21.3.0

### ISSUE THREAD

**Issue by mikicymulate** [allure-framework/allure-js#816]
**Describe the bug**
 Error: ENOENT: no such file or directory, open <file_name>.txt on Node.js v21.3.0 .
it work on  Node.js v20.10.0

**To Reproduce**
ruining playwright test on  Node.js version 21.3.0 with allure report
`reporter: [
        ["allure-playwright", {outputFolder: "./allure-results/"}]
        ]`

**Screenshots**

![image](https://github.com/allure-framework/allure-js/assets/106581694/2a1abe18-b1d5-48fc-a26c-72ab1b622837)

**Desktop (please complete the following information):**
 - OS: win 11
 - Version "allure-playwright": "^2.9.2"
 -  Node.js v21.3.0

`node:fs:2352
    return binding.writeFileUtf8(
                   ^

Error: ENOENT: no such file or directory, open 'C:\<path>\allure-results\d5deb228-a649-4d04-8224-36263284a346-attachment.txt'
    at writeFileSync (node:fs:2352:20)
    at FileSystemAllureWriter.writeAttachment (C:\dev\e2eautomation\Application\node_modules\allure-js-commons\src\writers\FileSystemAllureWriter.ts:27:18)
    at AllureRuntime.writeAttachment (C:\dev\e2eautomation\Application\node_modules\allure-js-commons\src\AllureRuntime.ts:47:17)
    at AllureReporter.onTestEnd (C:\dev\e2eautomation\Application\node_modules\allure-playwright\src\index.ts:202:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\<path>\\allure-results\\d5deb228-a649-4d04-8224-36263284a346-attachment.txt'
}

Node.js v21.3.0

Process finished with exit code 1
`

**Comment by epszaw** [comment]
@mikicymulate thank you for the highlight. Is it possible to provide a repository where I'll be able to reproduce the problem?

**Comment by mikicymulate** [comment]
Hi,
it was fixed on node version v21.5.0
